/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DOM Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getDOMCommand()
 * @model
 * @generated
 */
public interface DOMCommand extends Command
{
} // DOMCommand
