/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Read</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link www.imta.fr.browserautomation.seleniumDsl.Read#getElements <em>Elements</em>}</li>
 *   <li>{@link www.imta.fr.browserautomation.seleniumDsl.Read#getLinkText <em>Link Text</em>}</li>
 *   <li>{@link www.imta.fr.browserautomation.seleniumDsl.Read#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getRead()
 * @model
 * @generated
 */
public interface Read extends Command
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' attribute list.
   * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getRead_Elements()
   * @model unique="false"
   * @generated
   */
  EList<String> getElements();

  /**
   * Returns the value of the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link Text</em>' attribute.
   * @see #setLinkText(String)
   * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getRead_LinkText()
   * @model
   * @generated
   */
  String getLinkText();

  /**
   * Sets the value of the '{@link www.imta.fr.browserautomation.seleniumDsl.Read#getLinkText <em>Link Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link Text</em>' attribute.
   * @see #getLinkText()
   * @generated
   */
  void setLinkText(String value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getRead_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link www.imta.fr.browserautomation.seleniumDsl.Read#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

} // Read
