/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslFactory
 * @model kind="package"
 * @generated
 */
public interface SeleniumDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "seleniumDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imta.www/fr/browserautomation/SeleniumDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "seleniumDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SeleniumDslPackage eINSTANCE = www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl.init();

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.BrowserDslImpl <em>Browser Dsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.BrowserDslImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getBrowserDsl()
   * @generated
   */
  int BROWSER_DSL = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_DSL__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Browser Dsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_DSL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.CommandImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.OpenBrowserImpl <em>Open Browser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.OpenBrowserImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getOpenBrowser()
   * @generated
   */
  int OPEN_BROWSER = 2;

  /**
   * The number of structural features of the '<em>Open Browser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_BROWSER_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.DOMCommandImpl <em>DOM Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.DOMCommandImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getDOMCommand()
   * @generated
   */
  int DOM_COMMAND = 3;

  /**
   * The number of structural features of the '<em>DOM Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOM_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.GoToImpl <em>Go To</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.GoToImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getGoTo()
   * @generated
   */
  int GO_TO = 4;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO__URL = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go To</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.ClickImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getClick()
   * @generated
   */
  int CLICK = 5;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__ELEMENT = DOM_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = DOM_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.CopyImpl <em>Copy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.CopyImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getCopy()
   * @generated
   */
  int COPY = 6;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY__PROPERTY = DOM_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY__ELEMENT = DOM_COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY__KEY = DOM_COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Copy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY_FEATURE_COUNT = DOM_COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.PasteImpl <em>Paste</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.PasteImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getPaste()
   * @generated
   */
  int PASTE = 7;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASTE__ELEMENT = DOM_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Paste</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASTE_FEATURE_COUNT = DOM_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.InsertImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 8;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__ELEMENT = DOM_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__CONTENT = DOM_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = DOM_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SelectorImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 9;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__PREDICATE = 0;

  /**
   * The feature id for the '<em><b>Dom Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__DOM_TYPE = 1;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__ATTRIBUTES = 2;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__LABEL = 3;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__PROPERTIES = 4;

  /**
   * The feature id for the '<em><b>Parent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__PARENT = 5;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.AttributesImpl <em>Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.AttributesImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getAttributes()
   * @generated
   */
  int ATTRIBUTES = 10;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTES__ATTRIBUTES = 0;

  /**
   * The number of structural features of the '<em>Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ElementAttributeImpl <em>Element Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.ElementAttributeImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getElementAttribute()
   * @generated
   */
  int ELEMENT_ATTRIBUTE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Matcher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_ATTRIBUTE__MATCHER = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_ATTRIBUTE__VALUE = 2;

  /**
   * The number of structural features of the '<em>Element Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_ATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.ContentImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getContent()
   * @generated
   */
  int CONTENT = 12;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ClipboardContentImpl <em>Clipboard Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.ClipboardContentImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getClipboardContent()
   * @generated
   */
  int CLIPBOARD_CONTENT = 13;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIPBOARD_CONTENT__KEY = CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Clipboard Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIPBOARD_CONTENT_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.StringContentImpl <em>String Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.StringContentImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getStringContent()
   * @generated
   */
  int STRING_CONTENT = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONTENT__VALUE = CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONTENT_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.PropertiesImpl <em>Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.PropertiesImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getProperties()
   * @generated
   */
  int PROPERTIES = 15;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES__PROPERTIES = 0;

  /**
   * The number of structural features of the '<em>Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ElementPropertyImpl <em>Element Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.ElementPropertyImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getElementProperty()
   * @generated
   */
  int ELEMENT_PROPERTY = 16;

  /**
   * The feature id for the '<em><b>Negated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_PROPERTY__NEGATED = 0;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_PROPERTY__PROPERTY = 1;

  /**
   * The number of structural features of the '<em>Element Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.SelectorPredicateImpl <em>Selector Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SelectorPredicateImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getSelectorPredicate()
   * @generated
   */
  int SELECTOR_PREDICATE = 17;

  /**
   * The number of structural features of the '<em>Selector Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_PREDICATE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.AllConditionImpl <em>All Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.AllConditionImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getAllCondition()
   * @generated
   */
  int ALL_CONDITION = 18;

  /**
   * The number of structural features of the '<em>All Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_CONDITION_FEATURE_COUNT = SELECTOR_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.IntWithSuffixImpl <em>Int With Suffix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.IntWithSuffixImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getIntWithSuffix()
   * @generated
   */
  int INT_WITH_SUFFIX = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_WITH_SUFFIX__VALUE = 0;

  /**
   * The number of structural features of the '<em>Int With Suffix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_WITH_SUFFIX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.OrdinalConditionImpl <em>Ordinal Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.OrdinalConditionImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getOrdinalCondition()
   * @generated
   */
  int ORDINAL_CONDITION = 20;

  /**
   * The feature id for the '<em><b>Ordinal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDINAL_CONDITION__ORDINAL = SELECTOR_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ordinal Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDINAL_CONDITION_FEATURE_COUNT = SELECTOR_PREDICATE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.LastConditionImpl <em>Last Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.LastConditionImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getLastCondition()
   * @generated
   */
  int LAST_CONDITION = 21;

  /**
   * The number of structural features of the '<em>Last Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAST_CONDITION_FEATURE_COUNT = SELECTOR_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.FirstConditionImpl <em>First Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.FirstConditionImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getFirstCondition()
   * @generated
   */
  int FIRST_CONDITION = 22;

  /**
   * The number of structural features of the '<em>First Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIRST_CONDITION_FEATURE_COUNT = SELECTOR_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.VerifyImpl <em>Verify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.VerifyImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getVerify()
   * @generated
   */
  int VERIFY = 23;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__SELECTOR = DOM_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__PROPERTIES = DOM_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Verify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_FEATURE_COUNT = DOM_COMMAND_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.BrowserDsl <em>Browser Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Browser Dsl</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.BrowserDsl
   * @generated
   */
  EClass getBrowserDsl();

  /**
   * Returns the meta object for the containment reference list '{@link www.imta.fr.browserautomation.seleniumDsl.BrowserDsl#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.BrowserDsl#getCommands()
   * @see #getBrowserDsl()
   * @generated
   */
  EReference getBrowserDsl_Commands();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.OpenBrowser <em>Open Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open Browser</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.OpenBrowser
   * @generated
   */
  EClass getOpenBrowser();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.DOMCommand <em>DOM Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DOM Command</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.DOMCommand
   * @generated
   */
  EClass getDOMCommand();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.GoTo <em>Go To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go To</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.GoTo
   * @generated
   */
  EClass getGoTo();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.GoTo#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.GoTo#getUrl()
   * @see #getGoTo()
   * @generated
   */
  EAttribute getGoTo_Url();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Click#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Click#getElement()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Element();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Copy <em>Copy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Copy</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Copy
   * @generated
   */
  EClass getCopy();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Copy#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Copy#getProperty()
   * @see #getCopy()
   * @generated
   */
  EAttribute getCopy_Property();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Copy#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Copy#getElement()
   * @see #getCopy()
   * @generated
   */
  EReference getCopy_Element();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Copy#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Copy#getKey()
   * @see #getCopy()
   * @generated
   */
  EAttribute getCopy_Key();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Paste <em>Paste</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paste</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Paste
   * @generated
   */
  EClass getPaste();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Paste#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Paste#getElement()
   * @see #getPaste()
   * @generated
   */
  EReference getPaste_Element();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Insert#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Insert#getElement()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Element();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Insert#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Content</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Insert#getContent()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Content();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Selector#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector#getPredicate()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_Predicate();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Selector#getDomType <em>Dom Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dom Type</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector#getDomType()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_DomType();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Selector#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attributes</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector#getAttributes()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_Attributes();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Selector#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector#getLabel()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Label();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Selector#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Properties</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector#getProperties()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_Properties();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Selector#getParent <em>Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parent</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector#getParent()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_Parent();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Attributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attributes</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Attributes
   * @generated
   */
  EClass getAttributes();

  /**
   * Returns the meta object for the containment reference list '{@link www.imta.fr.browserautomation.seleniumDsl.Attributes#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Attributes#getAttributes()
   * @see #getAttributes()
   * @generated
   */
  EReference getAttributes_Attributes();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.ElementAttribute <em>Element Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element Attribute</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementAttribute
   * @generated
   */
  EClass getElementAttribute();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.ElementAttribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementAttribute#getName()
   * @see #getElementAttribute()
   * @generated
   */
  EAttribute getElementAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.ElementAttribute#getMatcher <em>Matcher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Matcher</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementAttribute#getMatcher()
   * @see #getElementAttribute()
   * @generated
   */
  EAttribute getElementAttribute_Matcher();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.ElementAttribute#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementAttribute#getValue()
   * @see #getElementAttribute()
   * @generated
   */
  EReference getElementAttribute_Value();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.ClipboardContent <em>Clipboard Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clipboard Content</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ClipboardContent
   * @generated
   */
  EClass getClipboardContent();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.ClipboardContent#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ClipboardContent#getKey()
   * @see #getClipboardContent()
   * @generated
   */
  EAttribute getClipboardContent_Key();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.StringContent <em>String Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Content</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.StringContent
   * @generated
   */
  EClass getStringContent();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.StringContent#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.StringContent#getValue()
   * @see #getStringContent()
   * @generated
   */
  EAttribute getStringContent_Value();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Properties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Properties</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Properties
   * @generated
   */
  EClass getProperties();

  /**
   * Returns the meta object for the containment reference list '{@link www.imta.fr.browserautomation.seleniumDsl.Properties#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Properties#getProperties()
   * @see #getProperties()
   * @generated
   */
  EReference getProperties_Properties();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.ElementProperty <em>Element Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element Property</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementProperty
   * @generated
   */
  EClass getElementProperty();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.ElementProperty#getNegated <em>Negated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Negated</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementProperty#getNegated()
   * @see #getElementProperty()
   * @generated
   */
  EAttribute getElementProperty_Negated();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.ElementProperty#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementProperty#getProperty()
   * @see #getElementProperty()
   * @generated
   */
  EAttribute getElementProperty_Property();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.SelectorPredicate <em>Selector Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector Predicate</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.SelectorPredicate
   * @generated
   */
  EClass getSelectorPredicate();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.AllCondition <em>All Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Condition</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.AllCondition
   * @generated
   */
  EClass getAllCondition();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.IntWithSuffix <em>Int With Suffix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int With Suffix</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.IntWithSuffix
   * @generated
   */
  EClass getIntWithSuffix();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.IntWithSuffix#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.IntWithSuffix#getValue()
   * @see #getIntWithSuffix()
   * @generated
   */
  EAttribute getIntWithSuffix_Value();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.OrdinalCondition <em>Ordinal Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ordinal Condition</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.OrdinalCondition
   * @generated
   */
  EClass getOrdinalCondition();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.OrdinalCondition#getOrdinal <em>Ordinal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ordinal</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.OrdinalCondition#getOrdinal()
   * @see #getOrdinalCondition()
   * @generated
   */
  EReference getOrdinalCondition_Ordinal();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.LastCondition <em>Last Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Last Condition</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.LastCondition
   * @generated
   */
  EClass getLastCondition();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.FirstCondition <em>First Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>First Condition</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.FirstCondition
   * @generated
   */
  EClass getFirstCondition();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Verify
   * @generated
   */
  EClass getVerify();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Verify#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Verify#getSelector()
   * @see #getVerify()
   * @generated
   */
  EReference getVerify_Selector();

  /**
   * Returns the meta object for the containment reference list '{@link www.imta.fr.browserautomation.seleniumDsl.Verify#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Verify#getProperties()
   * @see #getVerify()
   * @generated
   */
  EReference getVerify_Properties();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SeleniumDslFactory getSeleniumDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.BrowserDslImpl <em>Browser Dsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.BrowserDslImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getBrowserDsl()
     * @generated
     */
    EClass BROWSER_DSL = eINSTANCE.getBrowserDsl();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BROWSER_DSL__COMMANDS = eINSTANCE.getBrowserDsl_Commands();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.CommandImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.OpenBrowserImpl <em>Open Browser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.OpenBrowserImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getOpenBrowser()
     * @generated
     */
    EClass OPEN_BROWSER = eINSTANCE.getOpenBrowser();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.DOMCommandImpl <em>DOM Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.DOMCommandImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getDOMCommand()
     * @generated
     */
    EClass DOM_COMMAND = eINSTANCE.getDOMCommand();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.GoToImpl <em>Go To</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.GoToImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getGoTo()
     * @generated
     */
    EClass GO_TO = eINSTANCE.getGoTo();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO_TO__URL = eINSTANCE.getGoTo_Url();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.ClickImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__ELEMENT = eINSTANCE.getClick_Element();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.CopyImpl <em>Copy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.CopyImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getCopy()
     * @generated
     */
    EClass COPY = eINSTANCE.getCopy();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COPY__PROPERTY = eINSTANCE.getCopy_Property();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COPY__ELEMENT = eINSTANCE.getCopy_Element();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COPY__KEY = eINSTANCE.getCopy_Key();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.PasteImpl <em>Paste</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.PasteImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getPaste()
     * @generated
     */
    EClass PASTE = eINSTANCE.getPaste();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PASTE__ELEMENT = eINSTANCE.getPaste_Element();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.InsertImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__ELEMENT = eINSTANCE.getInsert_Element();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__CONTENT = eINSTANCE.getInsert_Content();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SelectorImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__PREDICATE = eINSTANCE.getSelector_Predicate();

    /**
     * The meta object literal for the '<em><b>Dom Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__DOM_TYPE = eINSTANCE.getSelector_DomType();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__ATTRIBUTES = eINSTANCE.getSelector_Attributes();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__LABEL = eINSTANCE.getSelector_Label();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__PROPERTIES = eINSTANCE.getSelector_Properties();

    /**
     * The meta object literal for the '<em><b>Parent</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__PARENT = eINSTANCE.getSelector_Parent();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.AttributesImpl <em>Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.AttributesImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getAttributes()
     * @generated
     */
    EClass ATTRIBUTES = eINSTANCE.getAttributes();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTES__ATTRIBUTES = eINSTANCE.getAttributes_Attributes();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ElementAttributeImpl <em>Element Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.ElementAttributeImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getElementAttribute()
     * @generated
     */
    EClass ELEMENT_ATTRIBUTE = eINSTANCE.getElementAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT_ATTRIBUTE__NAME = eINSTANCE.getElementAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Matcher</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT_ATTRIBUTE__MATCHER = eINSTANCE.getElementAttribute_Matcher();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT_ATTRIBUTE__VALUE = eINSTANCE.getElementAttribute_Value();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.ContentImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ClipboardContentImpl <em>Clipboard Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.ClipboardContentImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getClipboardContent()
     * @generated
     */
    EClass CLIPBOARD_CONTENT = eINSTANCE.getClipboardContent();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLIPBOARD_CONTENT__KEY = eINSTANCE.getClipboardContent_Key();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.StringContentImpl <em>String Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.StringContentImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getStringContent()
     * @generated
     */
    EClass STRING_CONTENT = eINSTANCE.getStringContent();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_CONTENT__VALUE = eINSTANCE.getStringContent_Value();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.PropertiesImpl <em>Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.PropertiesImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getProperties()
     * @generated
     */
    EClass PROPERTIES = eINSTANCE.getProperties();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTIES__PROPERTIES = eINSTANCE.getProperties_Properties();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ElementPropertyImpl <em>Element Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.ElementPropertyImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getElementProperty()
     * @generated
     */
    EClass ELEMENT_PROPERTY = eINSTANCE.getElementProperty();

    /**
     * The meta object literal for the '<em><b>Negated</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT_PROPERTY__NEGATED = eINSTANCE.getElementProperty_Negated();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT_PROPERTY__PROPERTY = eINSTANCE.getElementProperty_Property();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.SelectorPredicateImpl <em>Selector Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SelectorPredicateImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getSelectorPredicate()
     * @generated
     */
    EClass SELECTOR_PREDICATE = eINSTANCE.getSelectorPredicate();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.AllConditionImpl <em>All Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.AllConditionImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getAllCondition()
     * @generated
     */
    EClass ALL_CONDITION = eINSTANCE.getAllCondition();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.IntWithSuffixImpl <em>Int With Suffix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.IntWithSuffixImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getIntWithSuffix()
     * @generated
     */
    EClass INT_WITH_SUFFIX = eINSTANCE.getIntWithSuffix();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_WITH_SUFFIX__VALUE = eINSTANCE.getIntWithSuffix_Value();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.OrdinalConditionImpl <em>Ordinal Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.OrdinalConditionImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getOrdinalCondition()
     * @generated
     */
    EClass ORDINAL_CONDITION = eINSTANCE.getOrdinalCondition();

    /**
     * The meta object literal for the '<em><b>Ordinal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDINAL_CONDITION__ORDINAL = eINSTANCE.getOrdinalCondition_Ordinal();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.LastConditionImpl <em>Last Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.LastConditionImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getLastCondition()
     * @generated
     */
    EClass LAST_CONDITION = eINSTANCE.getLastCondition();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.FirstConditionImpl <em>First Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.FirstConditionImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getFirstCondition()
     * @generated
     */
    EClass FIRST_CONDITION = eINSTANCE.getFirstCondition();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.VerifyImpl <em>Verify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.VerifyImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getVerify()
     * @generated
     */
    EClass VERIFY = eINSTANCE.getVerify();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY__SELECTOR = eINSTANCE.getVerify_Selector();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY__PROPERTIES = eINSTANCE.getVerify_Properties();

  }

} //SeleniumDslPackage
