/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslFactory
 * @model kind="package"
 * @generated
 */
public interface SeleniumDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "seleniumDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imta.www/fr/browserautomation/SeleniumDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "seleniumDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SeleniumDslPackage eINSTANCE = www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl.init();

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.BrowserDslImpl <em>Browser Dsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.BrowserDslImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getBrowserDsl()
   * @generated
   */
  int BROWSER_DSL = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_DSL__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Browser Dsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_DSL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.CommandImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.OpenBrowserImpl <em>Open Browser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.OpenBrowserImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getOpenBrowser()
   * @generated
   */
  int OPEN_BROWSER = 2;

  /**
   * The number of structural features of the '<em>Open Browser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_BROWSER_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.GoToImpl <em>Go To</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.GoToImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getGoTo()
   * @generated
   */
  int GO_TO = 3;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO__URL = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go To</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.ClickImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getClick()
   * @generated
   */
  int CLICK = 4;

  /**
   * The feature id for the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__LINK_TEXT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Button Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__BUTTON_TEXT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Alt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__ALT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__VARIABLE = COMMAND_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.FillImpl <em>Fill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.FillImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getFill()
   * @generated
   */
  int FILL = 5;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__ELEMENT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__FIELD_NAME = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Text To Fill</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__TEXT_TO_FILL = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__VARIABLE = COMMAND_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Fill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SelectorImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 6;

  /**
   * The feature id for the '<em><b>Element Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__ELEMENT_TYPE = 0;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SelectImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 7;

  /**
   * The feature id for the '<em><b>Element Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__ELEMENT_TYPE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__VALUES = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.VerifyImpl <em>Verify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.VerifyImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getVerify()
   * @generated
   */
  int VERIFY = 8;

  /**
   * The feature id for the '<em><b>Text To Verify</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__TEXT_TO_VERIFY = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Link To Verify</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__LINK_TO_VERIFY = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__VARIABLE = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Verify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ReadImpl <em>Read</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.ReadImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getRead()
   * @generated
   */
  int READ = 9;

  /**
   * The feature id for the '<em><b>Elements</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__ELEMENTS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__LINK_TEXT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__NUMBER = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Read</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.UncheckImpl <em>Uncheck</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.UncheckImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getUncheck()
   * @generated
   */
  int UNCHECK = 10;

  /**
   * The number of structural features of the '<em>Uncheck</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCHECK_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ComboboxImpl <em>Combobox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.ComboboxImpl
   * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getCombobox()
   * @generated
   */
  int COMBOBOX = 11;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__ELEMENTS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Option</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__OPTION = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__LABEL = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Combobox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.BrowserDsl <em>Browser Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Browser Dsl</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.BrowserDsl
   * @generated
   */
  EClass getBrowserDsl();

  /**
   * Returns the meta object for the containment reference list '{@link www.imta.fr.browserautomation.seleniumDsl.BrowserDsl#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.BrowserDsl#getCommands()
   * @see #getBrowserDsl()
   * @generated
   */
  EReference getBrowserDsl_Commands();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.OpenBrowser <em>Open Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open Browser</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.OpenBrowser
   * @generated
   */
  EClass getOpenBrowser();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.GoTo <em>Go To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go To</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.GoTo
   * @generated
   */
  EClass getGoTo();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.GoTo#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.GoTo#getUrl()
   * @see #getGoTo()
   * @generated
   */
  EAttribute getGoTo_Url();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Click#getLinkText <em>Link Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link Text</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Click#getLinkText()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_LinkText();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Click#getButtonText <em>Button Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Button Text</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Click#getButtonText()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_ButtonText();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Click#getAlt <em>Alt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alt</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Click#getAlt()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_Alt();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Click#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Click#getVariable()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_Variable();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Fill <em>Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Fill
   * @generated
   */
  EClass getFill();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Fill#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Fill#getElement()
   * @see #getFill()
   * @generated
   */
  EReference getFill_Element();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Fill#getFieldName <em>Field Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Name</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Fill#getFieldName()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_FieldName();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Fill#getTextToFill <em>Text To Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text To Fill</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Fill#getTextToFill()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_TextToFill();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Fill#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Fill#getVariable()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_Variable();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Selector#getElementType <em>Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element Type</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector#getElementType()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_ElementType();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the containment reference '{@link www.imta.fr.browserautomation.seleniumDsl.Select#getElementType <em>Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element Type</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Select#getElementType()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_ElementType();

  /**
   * Returns the meta object for the attribute list '{@link www.imta.fr.browserautomation.seleniumDsl.Select#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Select#getValues()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_Values();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Verify
   * @generated
   */
  EClass getVerify();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Verify#getTextToVerify <em>Text To Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text To Verify</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Verify#getTextToVerify()
   * @see #getVerify()
   * @generated
   */
  EAttribute getVerify_TextToVerify();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Verify#getLinkToVerify <em>Link To Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link To Verify</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Verify#getLinkToVerify()
   * @see #getVerify()
   * @generated
   */
  EAttribute getVerify_LinkToVerify();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Verify#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Verify#getVariable()
   * @see #getVerify()
   * @generated
   */
  EAttribute getVerify_Variable();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Read <em>Read</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Read
   * @generated
   */
  EClass getRead();

  /**
   * Returns the meta object for the attribute list '{@link www.imta.fr.browserautomation.seleniumDsl.Read#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Elements</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Read#getElements()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_Elements();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Read#getLinkText <em>Link Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link Text</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Read#getLinkText()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_LinkText();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Read#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Read#getNumber()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_Number();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Uncheck <em>Uncheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uncheck</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Uncheck
   * @generated
   */
  EClass getUncheck();

  /**
   * Returns the meta object for class '{@link www.imta.fr.browserautomation.seleniumDsl.Combobox <em>Combobox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Combobox</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Combobox
   * @generated
   */
  EClass getCombobox();

  /**
   * Returns the meta object for the containment reference list '{@link www.imta.fr.browserautomation.seleniumDsl.Combobox#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Combobox#getElements()
   * @see #getCombobox()
   * @generated
   */
  EReference getCombobox_Elements();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Combobox#getOption <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Option</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Combobox#getOption()
   * @see #getCombobox()
   * @generated
   */
  EAttribute getCombobox_Option();

  /**
   * Returns the meta object for the attribute '{@link www.imta.fr.browserautomation.seleniumDsl.Combobox#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see www.imta.fr.browserautomation.seleniumDsl.Combobox#getLabel()
   * @see #getCombobox()
   * @generated
   */
  EAttribute getCombobox_Label();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SeleniumDslFactory getSeleniumDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.BrowserDslImpl <em>Browser Dsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.BrowserDslImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getBrowserDsl()
     * @generated
     */
    EClass BROWSER_DSL = eINSTANCE.getBrowserDsl();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BROWSER_DSL__COMMANDS = eINSTANCE.getBrowserDsl_Commands();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.CommandImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.OpenBrowserImpl <em>Open Browser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.OpenBrowserImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getOpenBrowser()
     * @generated
     */
    EClass OPEN_BROWSER = eINSTANCE.getOpenBrowser();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.GoToImpl <em>Go To</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.GoToImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getGoTo()
     * @generated
     */
    EClass GO_TO = eINSTANCE.getGoTo();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO_TO__URL = eINSTANCE.getGoTo_Url();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.ClickImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Link Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__LINK_TEXT = eINSTANCE.getClick_LinkText();

    /**
     * The meta object literal for the '<em><b>Button Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__BUTTON_TEXT = eINSTANCE.getClick_ButtonText();

    /**
     * The meta object literal for the '<em><b>Alt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__ALT = eINSTANCE.getClick_Alt();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__VARIABLE = eINSTANCE.getClick_Variable();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.FillImpl <em>Fill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.FillImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getFill()
     * @generated
     */
    EClass FILL = eINSTANCE.getFill();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL__ELEMENT = eINSTANCE.getFill_Element();

    /**
     * The meta object literal for the '<em><b>Field Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__FIELD_NAME = eINSTANCE.getFill_FieldName();

    /**
     * The meta object literal for the '<em><b>Text To Fill</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__TEXT_TO_FILL = eINSTANCE.getFill_TextToFill();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__VARIABLE = eINSTANCE.getFill_Variable();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SelectorImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Element Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__ELEMENT_TYPE = eINSTANCE.getSelector_ElementType();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SelectImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Element Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__ELEMENT_TYPE = eINSTANCE.getSelect_ElementType();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__VALUES = eINSTANCE.getSelect_Values();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.VerifyImpl <em>Verify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.VerifyImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getVerify()
     * @generated
     */
    EClass VERIFY = eINSTANCE.getVerify();

    /**
     * The meta object literal for the '<em><b>Text To Verify</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY__TEXT_TO_VERIFY = eINSTANCE.getVerify_TextToVerify();

    /**
     * The meta object literal for the '<em><b>Link To Verify</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY__LINK_TO_VERIFY = eINSTANCE.getVerify_LinkToVerify();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY__VARIABLE = eINSTANCE.getVerify_Variable();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ReadImpl <em>Read</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.ReadImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getRead()
     * @generated
     */
    EClass READ = eINSTANCE.getRead();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__ELEMENTS = eINSTANCE.getRead_Elements();

    /**
     * The meta object literal for the '<em><b>Link Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__LINK_TEXT = eINSTANCE.getRead_LinkText();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__NUMBER = eINSTANCE.getRead_Number();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.UncheckImpl <em>Uncheck</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.UncheckImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getUncheck()
     * @generated
     */
    EClass UNCHECK = eINSTANCE.getUncheck();

    /**
     * The meta object literal for the '{@link www.imta.fr.browserautomation.seleniumDsl.impl.ComboboxImpl <em>Combobox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.ComboboxImpl
     * @see www.imta.fr.browserautomation.seleniumDsl.impl.SeleniumDslPackageImpl#getCombobox()
     * @generated
     */
    EClass COMBOBOX = eINSTANCE.getCombobox();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMBOBOX__ELEMENTS = eINSTANCE.getCombobox_Elements();

    /**
     * The meta object literal for the '<em><b>Option</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMBOBOX__OPTION = eINSTANCE.getCombobox_Option();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMBOBOX__LABEL = eINSTANCE.getCombobox_Label();

  }

} //SeleniumDslPackage
