/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link www.imta.fr.browserautomation.seleniumDsl.TestCase#getName <em>Name</em>}</li>
 *   <li>{@link www.imta.fr.browserautomation.seleniumDsl.TestCase#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getTestCase()
 * @model
 * @generated
 */
public interface TestCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getTestCase_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link www.imta.fr.browserautomation.seleniumDsl.TestCase#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference list.
   * The list contents are of type {@link www.imta.fr.browserautomation.seleniumDsl.Command}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference list.
   * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getTestCase_Commands()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommands();

} // TestCase
