/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uncheck</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage#getUncheck()
 * @model
 * @generated
 */
public interface Uncheck extends Command
{
} // Uncheck
