/*
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SeleniumDslUiModule extends AbstractSeleniumDslUiModule {

	public SeleniumDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
