/*
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import www.imta.fr.browserautomation.SeleniumDslRuntimeModule;
import www.imta.fr.browserautomation.SeleniumDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SeleniumDslIdeSetup extends SeleniumDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SeleniumDslRuntimeModule(), new SeleniumDslIdeModule()));
	}
	
}
