/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.generator;

import com.google.common.base.Objects;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.xtext.example.mydsl1.myDsl.ClickCommand;
import org.xtext.example.mydsl1.myDsl.Command;
import org.xtext.example.mydsl1.myDsl.FillCommand;
import org.xtext.example.mydsl1.myDsl.Model;
import org.xtext.example.mydsl1.myDsl.NavigateToCommand;
import org.xtext.example.mydsl1.myDsl.OpenBrowserCommand;
import org.xtext.example.mydsl1.myDsl.SelectCommand;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    boolean _notEquals = (!Objects.equal(resource, null));
    if (_notEquals) {
      EObject _head = IterableExtensions.<EObject>head(resource.getContents());
      final Model model = ((Model) _head);
      final String driverCode = this.generateWebDriverCode(model);
      fsa.generateFile("src/generated/AutomationTest.java", driverCode);
    }
  }

  public String generateWebDriverCode(final Model model) {
    String _xblockexpression = null;
    {
      final Function1<Command, CharSequence> _function = (Command it) -> {
        return this.generateCommandCode(it);
      };
      final String commandsCode = IterableExtensions.join(ListExtensions.<Command, CharSequence>map(model.getCommands(), _function), "\n\n");
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("package src.generated; // Update the package declaration");
      _builder.newLine();
      _builder.append("import org.openqa.selenium.By;");
      _builder.newLine();
      _builder.append("import org.openqa.selenium.WebDriver;");
      _builder.newLine();
      _builder.append("import org.openqa.selenium.chrome.ChromeDriver;");
      _builder.newLine();
      _builder.append("import org.openqa.selenium.chrome.ChromeOptions;");
      _builder.newLine();
      _builder.append("import org.openqa.selenium.WebElement;");
      _builder.newLine();
      _builder.append("\t  ");
      _builder.newLine();
      _builder.append("public class AutomationTest {");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("public static void main(String[] args) {\t  ");
      _builder.newLine();
      _builder.append("    ");
      _builder.newLine();
      String _plus = (_builder.toString() + commandsCode);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("  ");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      _xblockexpression = (_plus + _builder_1);
    }
    return _xblockexpression;
  }

  public CharSequence generateCommandCode(final Command command) {
    CharSequence _switchResult = null;
    boolean _matched = false;
    if (command instanceof OpenBrowserCommand) {
      _matched=true;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("WebDriver driver = (WebDriver) new ChromeDriver();");
      _builder.newLine();
      _switchResult = _builder;
    }
    if (!_matched) {
      if (command instanceof NavigateToCommand) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("driver.get(\"");
        String _url = ((NavigateToCommand)command).getUrl();
        String _plus = (_builder.toString() + _url);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("\");");
        _builder_1.newLine();
        _switchResult = (_plus + _builder_1);
      }
    }
    if (!_matched) {
      if (command instanceof ClickCommand) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("WebElement element = driver.findElement(By.linkText(\"");
        String _elementText = ((ClickCommand)command).getElementText();
        String _plus = (_builder.toString() + _elementText);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("\"));");
        _builder_1.newLine();
        _builder_1.append("\t        ");
        _builder_1.append("element.click();");
        _builder_1.newLine();
        _switchResult = (_plus + _builder_1);
      }
    }
    if (!_matched) {
      if (command instanceof FillCommand) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("WebElement element = driver.findElement(By.name(\"");
        String _fieldName = ((FillCommand)command).getFieldName();
        String _plus = (_builder.toString() + _fieldName);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("\"));");
        _builder_1.newLine();
        _builder_1.append("\t        ");
        _builder_1.append("element.sendKeys(\"");
        String _plus_1 = (_plus + _builder_1);
        String _fieldValue = ((FillCommand)command).getFieldValue();
        String _plus_2 = (_plus_1 + _fieldValue);
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.append("\");");
        _builder_2.newLine();
        _switchResult = (_plus_2 + _builder_2);
      }
    }
    if (!_matched) {
      if (command instanceof SelectCommand) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("WebElement element = driver.findElement(By.name(\"");
        String _checkboxName = ((SelectCommand)command).getCheckboxName();
        String _plus = (_builder.toString() + _checkboxName);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("\"));");
        _builder_1.newLine();
        _builder_1.append("\t        ");
        _builder_1.append("element.click();");
        _builder_1.newLine();
        _switchResult = (_plus + _builder_1);
      }
    }
    if (!_matched) {
      _switchResult = "";
    }
    return _switchResult;
  }
}
