/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl.impl;

import org.eclipse.emf.ecore.EClass;

import www.imta.fr.browserautomation.seleniumDsl.DefaultFirstPredicate;
import www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Default First Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DefaultFirstPredicateImpl extends SelectorPredicateImpl implements DefaultFirstPredicate
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefaultFirstPredicateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SeleniumDslPackage.Literals.DEFAULT_FIRST_PREDICATE;
  }

} //DefaultFirstPredicateImpl
