/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl.impl;

import org.eclipse.emf.ecore.EClass;

import www.imta.fr.browserautomation.seleniumDsl.LastPredicate;
import www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Last Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LastPredicateImpl extends SelectorPredicateImpl implements LastPredicate
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LastPredicateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SeleniumDslPackage.Literals.LAST_PREDICATE;
  }

} //LastPredicateImpl
