/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl1.myDsl.MyDslPackage;
import org.xtext.example.mydsl1.myDsl.OpenBrowser;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Open Browser</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OpenBrowserImpl extends CommandImpl implements OpenBrowser
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OpenBrowserImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPEN_BROWSER;
  }

} //OpenBrowserImpl
