/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl1.myDsl.MyDslPackage;
import org.xtext.example.mydsl1.myDsl.VerifyCommand;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Verify Command</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.impl.VerifyCommandImpl#getVerifyString <em>Verify String</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VerifyCommandImpl extends CommandImpl implements VerifyCommand
{
  /**
   * The default value of the '{@link #getVerifyString() <em>Verify String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerifyString()
   * @generated
   * @ordered
   */
  protected static final String VERIFY_STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVerifyString() <em>Verify String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerifyString()
   * @generated
   * @ordered
   */
  protected String verifyString = VERIFY_STRING_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VerifyCommandImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.VERIFY_COMMAND;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVerifyString()
  {
    return verifyString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVerifyString(String newVerifyString)
  {
    String oldVerifyString = verifyString;
    verifyString = newVerifyString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VERIFY_COMMAND__VERIFY_STRING, oldVerifyString, verifyString));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.VERIFY_COMMAND__VERIFY_STRING:
        return getVerifyString();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.VERIFY_COMMAND__VERIFY_STRING:
        setVerifyString((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VERIFY_COMMAND__VERIFY_STRING:
        setVerifyString(VERIFY_STRING_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VERIFY_COMMAND__VERIFY_STRING:
        return VERIFY_STRING_EDEFAULT == null ? verifyString != null : !VERIFY_STRING_EDEFAULT.equals(verifyString);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (verifyString: ");
    result.append(verifyString);
    result.append(')');
    return result.toString();
  }

} //VerifyCommandImpl
