/**
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.seleniumDsl.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import www.imta.fr.browserautomation.seleniumDsl.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see www.imta.fr.browserautomation.seleniumDsl.SeleniumDslPackage
 * @generated
 */
public class SeleniumDslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static SeleniumDslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SeleniumDslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = SeleniumDslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SeleniumDslSwitch<Adapter> modelSwitch =
    new SeleniumDslSwitch<Adapter>()
    {
      @Override
      public Adapter caseBrowserDsl(BrowserDsl object)
      {
        return createBrowserDslAdapter();
      }
      @Override
      public Adapter caseCommand(Command object)
      {
        return createCommandAdapter();
      }
      @Override
      public Adapter caseOpenBrowser(OpenBrowser object)
      {
        return createOpenBrowserAdapter();
      }
      @Override
      public Adapter caseDOMCommand(DOMCommand object)
      {
        return createDOMCommandAdapter();
      }
      @Override
      public Adapter caseGoTo(GoTo object)
      {
        return createGoToAdapter();
      }
      @Override
      public Adapter caseClick(Click object)
      {
        return createClickAdapter();
      }
      @Override
      public Adapter caseCopy(Copy object)
      {
        return createCopyAdapter();
      }
      @Override
      public Adapter casePaste(Paste object)
      {
        return createPasteAdapter();
      }
      @Override
      public Adapter caseInsert(Insert object)
      {
        return createInsertAdapter();
      }
      @Override
      public Adapter caseSelector(Selector object)
      {
        return createSelectorAdapter();
      }
      @Override
      public Adapter caseAttributes(Attributes object)
      {
        return createAttributesAdapter();
      }
      @Override
      public Adapter caseElementAttribute(ElementAttribute object)
      {
        return createElementAttributeAdapter();
      }
      @Override
      public Adapter caseContent(Content object)
      {
        return createContentAdapter();
      }
      @Override
      public Adapter caseClipboardContent(ClipboardContent object)
      {
        return createClipboardContentAdapter();
      }
      @Override
      public Adapter caseStringContent(StringContent object)
      {
        return createStringContentAdapter();
      }
      @Override
      public Adapter caseProperties(Properties object)
      {
        return createPropertiesAdapter();
      }
      @Override
      public Adapter caseElementProperty(ElementProperty object)
      {
        return createElementPropertyAdapter();
      }
      @Override
      public Adapter caseSelectorPredicate(SelectorPredicate object)
      {
        return createSelectorPredicateAdapter();
      }
      @Override
      public Adapter caseAllPredicate(AllPredicate object)
      {
        return createAllPredicateAdapter();
      }
      @Override
      public Adapter caseOrdinalPredicate(OrdinalPredicate object)
      {
        return createOrdinalPredicateAdapter();
      }
      @Override
      public Adapter caseLastPredicate(LastPredicate object)
      {
        return createLastPredicateAdapter();
      }
      @Override
      public Adapter caseDefaultFirstPredicate(DefaultFirstPredicate object)
      {
        return createDefaultFirstPredicateAdapter();
      }
      @Override
      public Adapter caseVerify(Verify object)
      {
        return createVerifyAdapter();
      }
      @Override
      public Adapter caseOrdinalInteger(OrdinalInteger object)
      {
        return createOrdinalIntegerAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.BrowserDsl <em>Browser Dsl</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.BrowserDsl
   * @generated
   */
  public Adapter createBrowserDslAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Command
   * @generated
   */
  public Adapter createCommandAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.OpenBrowser <em>Open Browser</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.OpenBrowser
   * @generated
   */
  public Adapter createOpenBrowserAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.DOMCommand <em>DOM Command</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.DOMCommand
   * @generated
   */
  public Adapter createDOMCommandAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.GoTo <em>Go To</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.GoTo
   * @generated
   */
  public Adapter createGoToAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Click
   * @generated
   */
  public Adapter createClickAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Copy <em>Copy</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Copy
   * @generated
   */
  public Adapter createCopyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Paste <em>Paste</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Paste
   * @generated
   */
  public Adapter createPasteAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Insert
   * @generated
   */
  public Adapter createInsertAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Selector
   * @generated
   */
  public Adapter createSelectorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Attributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Attributes
   * @generated
   */
  public Adapter createAttributesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.ElementAttribute <em>Element Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementAttribute
   * @generated
   */
  public Adapter createElementAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Content
   * @generated
   */
  public Adapter createContentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.ClipboardContent <em>Clipboard Content</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.ClipboardContent
   * @generated
   */
  public Adapter createClipboardContentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.StringContent <em>String Content</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.StringContent
   * @generated
   */
  public Adapter createStringContentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Properties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Properties
   * @generated
   */
  public Adapter createPropertiesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.ElementProperty <em>Element Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.ElementProperty
   * @generated
   */
  public Adapter createElementPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.SelectorPredicate <em>Selector Predicate</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.SelectorPredicate
   * @generated
   */
  public Adapter createSelectorPredicateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.AllPredicate <em>All Predicate</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.AllPredicate
   * @generated
   */
  public Adapter createAllPredicateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.OrdinalPredicate <em>Ordinal Predicate</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.OrdinalPredicate
   * @generated
   */
  public Adapter createOrdinalPredicateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.LastPredicate <em>Last Predicate</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.LastPredicate
   * @generated
   */
  public Adapter createLastPredicateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.DefaultFirstPredicate <em>Default First Predicate</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.DefaultFirstPredicate
   * @generated
   */
  public Adapter createDefaultFirstPredicateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.Verify
   * @generated
   */
  public Adapter createVerifyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link www.imta.fr.browserautomation.seleniumDsl.OrdinalInteger <em>Ordinal Integer</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see www.imta.fr.browserautomation.seleniumDsl.OrdinalInteger
   * @generated
   */
  public Adapter createOrdinalIntegerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //SeleniumDslAdapterFactory
