/*
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.ui.tests;

import com.google.inject.Injector;
import fr.imt.amantheo.dsl.selenium.ui.internal.SeleniumActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SeleniumDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SeleniumActivator.getInstance().getInjector("www.imta.fr.browserautomation.SeleniumDsl");
	}

}
