/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.Click#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getClick()
 * @model
 * @generated
 */
public interface Click extends DOMCommand
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(Selector)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getClick_Element()
   * @model containment="true"
   * @generated
   */
  Selector getElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.Click#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(Selector value);

} // Click
