/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.ClickCommand#getElementText <em>Element Text</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getClickCommand()
 * @model
 * @generated
 */
public interface ClickCommand extends Command
{
  /**
   * Returns the value of the '<em><b>Element Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Text</em>' attribute.
   * @see #setElementText(String)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getClickCommand_ElementText()
   * @model
   * @generated
   */
  String getElementText();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.ClickCommand#getElementText <em>Element Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Text</em>' attribute.
   * @see #getElementText()
   * @generated
   */
  void setElementText(String value);

} // ClickCommand
