/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.ElementAttribute#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.ElementAttribute#getMatcher <em>Matcher</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.ElementAttribute#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getElementAttribute()
 * @model
 * @generated
 */
public interface ElementAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getElementAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.ElementAttribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Matcher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Matcher</em>' attribute.
   * @see #setMatcher(String)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getElementAttribute_Matcher()
   * @model
   * @generated
   */
  String getMatcher();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.ElementAttribute#getMatcher <em>Matcher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Matcher</em>' attribute.
   * @see #getMatcher()
   * @generated
   */
  void setMatcher(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Content)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getElementAttribute_Value()
   * @model containment="true"
   * @generated
   */
  Content getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.ElementAttribute#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Content value);

} // ElementAttribute
