/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Open Browser</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getOpenBrowser()
 * @model
 * @generated
 */
public interface OpenBrowser extends Command
{
} // OpenBrowser
