/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Read Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.ReadCommand#getElementText <em>Element Text</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.ReadCommand#getVariableName <em>Variable Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getReadCommand()
 * @model
 * @generated
 */
public interface ReadCommand extends Command
{
  /**
   * Returns the value of the '<em><b>Element Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Text</em>' attribute.
   * @see #setElementText(String)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getReadCommand_ElementText()
   * @model
   * @generated
   */
  String getElementText();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.ReadCommand#getElementText <em>Element Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Text</em>' attribute.
   * @see #getElementText()
   * @generated
   */
  void setElementText(String value);

  /**
   * Returns the value of the '<em><b>Variable Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Name</em>' attribute.
   * @see #setVariableName(String)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getReadCommand_VariableName()
   * @model
   * @generated
   */
  String getVariableName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.ReadCommand#getVariableName <em>Variable Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Name</em>' attribute.
   * @see #getVariableName()
   * @generated
   */
  void setVariableName(String value);

} // ReadCommand
