/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.SelectCommand#getCheckboxName <em>Checkbox Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getSelectCommand()
 * @model
 * @generated
 */
public interface SelectCommand extends Command
{
  /**
   * Returns the value of the '<em><b>Checkbox Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Checkbox Name</em>' attribute.
   * @see #setCheckboxName(String)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getSelectCommand_CheckboxName()
   * @model
   * @generated
   */
  String getCheckboxName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.SelectCommand#getCheckboxName <em>Checkbox Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Checkbox Name</em>' attribute.
   * @see #getCheckboxName()
   * @generated
   */
  void setCheckboxName(String value);

} // SelectCommand
