/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selector Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getSelectorPredicate()
 * @model
 * @generated
 */
public interface SelectorPredicate extends EObject
{
} // SelectorPredicate
