/*
 * generated by Xtext 2.32.0
 */
package www.imta.fr.browserautomation.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import www.imta.fr.browserautomation.services.SeleniumDslGrammarAccess;

@SuppressWarnings("all")
public class SeleniumDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SeleniumDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_GoTo_URLKeyword_3_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SeleniumDslGrammarAccess) access;
		match_GoTo_URLKeyword_3_1_q = new TokenAlias(false, true, grammarAccess.getGoToAccess().getURLKeyword_3_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_GoTo_URLKeyword_3_1_q.equals(syntax))
				emit_GoTo_URLKeyword_3_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'URL'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'go' 'to' 'url' (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_GoTo_URLKeyword_3_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
